---
- name: Crear directorios para alumno y equipo
  file:
    path: "/tmp/2do_parcial/{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - alumno
    - equipo

- name: Generar archivo datos_alumno.txt con template
  template:
    src: datos_alumno.txt.j2
    dest: /tmp/2do_parcial/alumno/datos_alumno.txt

- name: Generar archivo datos_equipo.txt con template
  template:
    src: datos_equipo.txt.j2
    dest: /tmp/2do_parcial/equipo/datos_equipo.txt

- name: Configurar sudoers para 2PSupervisores sin password
  copy:
    dest: /etc/sudoers.d/2PSupervisores
    content: '%2PSupervisores ALL=(ALL) NOPASSWD: ALL'
    mode: '0440'
